/* =====================================================================
   商品資料檔  —  內容照 Discord「善武工作室」各販售頻道抄的
   要新增 / 修改商品，只改這個檔案
   ---------------------------------------------------------------------
   id        : 英文代號（網址會用到，不可重複）
   name      : 商品名稱
   category  : 分類代號，必須是 CATEGORIES 裡的 key
   tagline   : 一句話簡介（卡片上顯示）
   price     : 數字（新台幣），填 null 代表「價格請洽詢」
   priceText : 價格不是單一數字時用這個（例如 FiveM 加密 / 開源兩種價）
   badge     : 卡片標籤，例如 "主打"、"新品"，不需要就留 ""
   images    : 圖片路徑陣列，第一張是封面（放在 assets/img/dc/）。沒有圖就填 []
   features  : 內容物 / 規格
   details   : 說明段落
   notes     : 備註
   ===================================================================== */

const STUDIO = {
  name: "善武工作室",
  intro: "我們做 GTA V 的台灣警車：Outlander、Camry，塗裝照台灣現役警車做，車牌、縣市、分局編號免費幫你改。看上哪台，到 Discord 開服務單就好。",
  heroImage: "assets/img/dc/outlander-1.jpg",
  otherDesc: "除了車以外，也有警用制服、插件中文翻譯、光影、FiveM 插件。需要的一起開單問。",
  orderNote: "採優先付款後交貨",
  pricingNote: "本工作室商品提供免費代裝服務，其餘服務及價格如下",
  contactText: "購買或詢問都在 Discord 開服務單，會有客服人員處理。目前只接受轉帳。",
  // 第一個聯絡方式會當作「我要買」按鈕的連結
  contacts: [
    { label: "Discord", url: "https://discord.gg/wtJyScvXVB", display: "discord.gg/wtJyScvXVB（進去開 🛎️服務單🛎️）" },
  ],
};

const CATEGORIES = {
  all:      { label: "全部" },
  vehicle:  { label: "台灣警車", desc: "收取的是警燈與警用塗裝的製作費，不是販售原車。目前僅有 replace 版本。" },
  eup:      { label: "EUP 警用服飾", desc: "內部均有安裝教學，怕太複雜也可以免費代裝。" },
  plugin:   { label: "警用插件中文翻譯", desc: "收取的是翻譯手工費，不是販售原插件，原插件要自己先下載。左上角字體無法正常顯示，其餘正常。" },
  lighting: { label: "光影", desc: "FiveM 和單機都能用。代買其他工作室的光影可以開工單問；代裝要多加 50 元手續。" },
  fivem:    { label: "FiveM 插件", desc: "只供 FiveM 伺服器使用，ESX 架構、OX 系統 1.10 適用，QB / QBX 不可用。加密版與開源版兩種價格。" },
  free:     { label: "免費區", desc: "免費釋出，直接拿去用。" },
};

/* 怎麼買（照 Discord「如何購買」頻道） */
const HOW_TO_BUY = [
  "到 Discord 伺服器的「🛎️服務單🛎️」頻道，按「點我開啟服務單」。",
  "客服人員會在服務單裡跟你確認商品與價格，對商品有疑慮也可以先在這裡問。",
  "先付款後交貨，目前只接受轉帳。交貨後需要代裝的話直接在同一張單說。",
];

const PRODUCTS = [
  /* ------------------------------------------------------------ 車輛 */
  {
    id: "outlander-2018",
    name: "Mitsubishi Outlander 2018 警車",
    category: "vehicle",
    tagline: "台灣警用黑白塗裝，車牌、縣市、分局編號免費自訂。",
    price: 350,
    unit: "輛",
    badge: "主打",
    images: [
      "assets/img/dc/outlander-1.jpg",
      "assets/img/dc/outlander-2.jpg",
      "assets/img/dc/outlander-3.jpg",
      "assets/img/dc/outlander-4.jpg",
      "assets/img/dc/outlander-5.jpg",
      "assets/img/dc/outlander-6.jpg",
    ],
    features: ["免費車牌、縣市、分局編號自訂", "警燈與警用塗裝", "replace 版本"],
    details: [],
    notes: ["收取費用為警燈、更改為警用塗裝之費用，非販售原車輛。", "僅有 replace。"],
  },
  {
    id: "camry-2021",
    name: "Toyota Camry 2021 警車",
    category: "vehicle",
    tagline: "台灣警用黑白塗裝，車牌、縣市、分局編號免費自訂。",
    price: 350,
    unit: "輛",
    badge: "",
    images: [
      "assets/img/dc/camry-1.jpg",
      "assets/img/dc/camry-2.jpg",
      "assets/img/dc/camry-3.jpg",
      "assets/img/dc/camry-4.jpg",
      "assets/img/dc/camry-5.jpg",
      "assets/img/dc/camry-6.jpg",
    ],
    features: ["免費車牌、縣市、分局編號自訂", "警燈與警用塗裝", "replace 版本"],
    details: [],
    notes: ["收取費用為警燈、更改為警用塗裝之費用，非販售原車輛。", "僅有 replace。"],
  },

  /* ------------------------------------------------------------ EUP */
  {
    id: "eup-uniform",
    name: "警用制服",
    category: "eup",
    tagline: "每個縣市 32 件制服，全台縣市臂章都有，男女、長短袖皆有。",
    price: 200,
    unit: "套",
    badge: "",
    images: [
      "assets/img/dc/eup-uniform-1.jpg",
      "assets/img/dc/eup-uniform-2.jpg",
      "assets/img/dc/eup-uniform-f-1.jpg",
      "assets/img/dc/eup-uniform-f-2.jpg",
      "assets/img/dc/eup-uniform-f-3.jpg",
      "assets/img/dc/eup-uniform-f-4.jpg",
    ],
    features: [
      "長短袖",
      "一線三 ～ 兩線三制服",
      "交通制服",
      "國道制服",
      "保一總隊霹靂小組 ～ 保七總隊霹靂小組制服",
      "警用長褲",
      "消防防火服、消防制服",
      "警用安全帽",
      "UB 設定及翻譯",
    ],
    details: ["每個縣市有 32 件制服。內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: ["全台灣的縣市臂章都有、男女皆有、長短皆有。", "女版與男版的長袖與短袖制服皆有。"],
  },
  {
    id: "eup-vest",
    name: "防彈衣及背心",
    category: "eup",
    tagline: "13 件防彈衣，附安裝教學。",
    price: 120,
    unit: "套",
    badge: "",
    images: [
      "assets/img/dc/eup-vest-1.jpg",
      "assets/img/dc/eup-vest-2.jpg",
      "assets/img/dc/eup-vest-f-1.jpg",
      "assets/img/dc/eup-vest-f-2.jpg",
      "assets/img/dc/eup-vest-f-3.jpg",
      "assets/img/dc/eup-vest-f-4.jpg",
    ],
    features: ["13 件防彈衣", "1 份安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: ["僅有男版防彈衣。"],
  },

  /* ------------------------------------------------------------ 中文翻譯 */
  {
    id: "zh-lspdfr",
    name: "LSPDFR 核心中文翻譯",
    category: "plugin",
    tagline: "LSPDFR 核心 + F4 修改器中文翻譯，附安裝教學。",
    price: 60,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/plug-lspdfr-4.jpg", "assets/img/dc/plug-lspdfr-1.jpg", "assets/img/dc/plug-lspdfr-2.jpg", "assets/img/dc/plug-lspdfr-3.jpg"],
    features: ["LSPDFR 核心中文翻譯", "F4 修改器中文翻譯", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: [
      "原檔案為 LSPDFR（lcpdfr.com）與 Script Hook V（dev-c.com），必須先下載才能裝中文翻譯。",
      "收取費用為翻譯的手工費用，並非販售原插件。",
      "左上角字體無法正常顯示，其餘正常。",
    ],
  },
  {
    id: "zh-stp",
    name: "Stop The Ped 中文翻譯",
    category: "plugin",
    tagline: "攔停選單、市民對話全部中文，附安裝教學。",
    price: 60,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/plug-stp-1.jpg", "assets/img/dc/plug-stp-2.jpg", "assets/img/dc/plug-stp-3.jpg", "assets/img/dc/plug-stp-4.jpg"],
    features: ["Stop The Ped 中文翻譯", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: [
      "原檔案為 Stop The Ped（bejoijo.com），必須先下載才能裝中文翻譯。",
      "收取費用為翻譯的手工費用，並非販售原插件。",
      "左上角字體無法正常顯示，其餘正常。",
    ],
  },
  {
    id: "zh-grammarpolice",
    name: "GrammarPolice 手持無線電中文翻譯",
    category: "plugin",
    tagline: "無線電介面中文化，連圖片檔一起改。",
    price: 30,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/plug-grammar-1.jpg", "assets/img/dc/plug-grammar-2.jpg", "assets/img/dc/plug-grammar-3.jpg", "assets/img/dc/plug-grammar-4.jpg"],
    features: ["GrammarPolice 手持無線電中文翻譯", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: [
      "原檔案為 GrammarPolice（lcpdfr.com），必須先下載才能裝中文翻譯。",
      "收取費用為翻譯及更改圖片檔的手工費用，並非販售原插件。",
    ],
  },
  {
    id: "zh-ultimate-backup",
    name: "Ultimate Backup 中文翻譯",
    category: "plugin",
    tagline: "支援選單中文化，附安裝教學。",
    price: 20,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/plug-ub-1.jpg", "assets/img/dc/plug-ub-2.jpg", "assets/img/dc/plug-ub-3.jpg", "assets/img/dc/plug-ub-4.jpg"],
    features: ["Ultimate Backup 中文翻譯", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: [
      "原檔案為 Ultimate Backup（bejoijo.com），必須先下載才能裝中文翻譯。",
      "收取費用為翻譯的手工費用，並非販售原插件。",
      "左上角字體無法正常顯示，其餘正常。",
    ],
  },
  {
    id: "zh-compulite",
    name: "CompuLite 中文翻譯",
    category: "plugin",
    tagline: "警用查詢系統中文化，附安裝教學。",
    price: 20,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/plug-compulite-1.jpg", "assets/img/dc/plug-compulite-2.jpg", "assets/img/dc/plug-compulite-3.jpg", "assets/img/dc/plug-compulite-4.jpg"],
    features: ["CompuLite 中文翻譯", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。"],
    notes: [
      "原檔案為 CompuLite（bejoijo.com），必須先下載才能裝中文翻譯。",
      "收取費用為翻譯的手工費用，並非販售原插件。",
      "左上角字體無法正常顯示，其餘正常。",
    ],
  },
  {
    id: "siren-pack",
    name: "警笛包",
    category: "plugin",
    tagline: "警車、警用機車、消防車、救護車警笛喇叭，含 ELS 設定檔。",
    price: 80,
    unit: "包",
    badge: "",
    images: ["assets/img/dc/siren-yt.jpg"],
    video: "https://youtu.be/PngJy2MBmBA",
    features: ["警笛包", "ELS 設定檔", "安裝教學"],
    details: ["內部均有安裝教學，如果擔心安裝教學太複雜，我們也有提供免費代裝服務。展示影片請看上方連結。"],
    notes: ["此警笛包包含警車、警用機車、消防車、救護車警笛喇叭。"],
  },

  /* ------------------------------------------------------------ 光影 */
  {
    id: "quantv",
    name: "QuantV 光影",
    category: "lighting",
    tagline: "FiveM 和單機都能用。",
    price: 300,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/light-quantv-1.jpg"],
    features: ["QuantV 光影", "FiveM / 單機"],
    details: [],
    notes: ["需要代裝要多加 50 元手續。", "如果需要代買其他工作室的光影可以開工單詢問。"],
  },
  {
    id: "quantv-nve",
    name: "QuantV 混 NVE 光影",
    category: "lighting",
    tagline: "QuantV 混 NVE，FiveM 和單機都能用。",
    price: 900,
    unit: "份",
    badge: "",
    images: ["assets/img/dc/light-nve-1.jpg"],
    features: ["QuantV 混 NVE", "FiveM / 單機"],
    details: [],
    notes: ["需要代裝要多加 50 元手續。", "如果需要代買其他工作室的光影可以開工單詢問。"],
  },

  /* ------------------------------------------------------------ FiveM 插件 */
  {
    id: "fivem-objection",
    name: "台灣臨檢異議單插件",
    category: "fivem",
    tagline: "在遊戲內給玩家使用異議單，含 DC 後台。",
    price: null,
    priceText: "加密 700 / 開源 1200",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-objection-1.jpg", "assets/img/dc/fivem-objection-2.jpg", "assets/img/dc/fivem-objection-3.jpg"],
    features: ["OX 系統，1.10 適用", "含 DC 後台", "須圖片可提供"],
    details: [],
    notes: ["此插件是 ESX 架構，QB 或 QBX 不可用。"],
  },
  {
    id: "fivem-good-citizen",
    name: "台灣良民證申請",
    category: "fivem",
    tagline: "玩家可申請良民證，其他市民也看得到，含 DC 後台。",
    price: null,
    priceText: "加密 700 / 開源 1200",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-goodcitizen-1.jpg"],
    features: ["OX 系統，1.10 適用", "含 DC 後台", "須圖片可提供"],
    details: [],
    notes: ["此插件是 ESX 架構，QB 或 QBX 不可用。"],
  },
  {
    id: "fivem-rent",
    name: "租房系統",
    category: "fivem",
    tagline: "在遊戲內租房子，含 DC 後台。",
    price: null,
    priceText: "加密 700 / 開源 1300",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-rent-1.jpg"],
    features: ["OX 系統，1.10 適用", "含 DC 後台"],
    details: ["圖片為 Discord 展示影片的截圖。"],
    notes: ["此插件是 ESX 架構，QB 或 QBX 不可用。"],
  },
  {
    id: "fivem-admin-panel",
    name: "管理面板",
    category: "fivem",
    tagline: "可自訂一按鍵，自帶天氣同步、換衣服選單等。",
    price: null,
    priceText: "加密 700 / 開源 1600",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-admin-panel-1.jpg"],
    features: ["OX 系統，1.10 適用", "天氣同步系統", "換衣服選單"],
    details: ["圖片為 Discord 展示影片的截圖。"],
    notes: ["此插件是 ESX 架構，QB 或 QBX 不可用。"],
  },
  {
    id: "fivem-panic",
    name: "警員緊急按鈕",
    category: "fivem",
    tagline: "警員手動啟用或倒地自動觸發警報。",
    price: null,
    priceText: "加密 200 / 開源 500",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-panic-1.jpg"],
    features: ["OX 系統，1.10 適用", "須圖片可提供"],
    details: ["圖片為 Discord 展示影片的截圖。"],
    notes: ["此插件是 ESX 架構，QB 或 QBX 不可用。"],
  },
  {
    id: "fivem-admin-help",
    name: "管理員求助",
    category: "fivem",
    tagline: "打 /adminhelp 加上要說的字就好。",
    price: null,
    priceText: "加密 400 / 開源 700",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-adminhelp-1.jpg"],
    features: ["/adminhelp 指令"],
    details: [],
    notes: [],
  },
  {
    id: "fivem-job-map",
    name: "公職地圖定位系統",
    category: "fivem",
    tagline: "定位上班玩家的座標，可新增職位。",
    price: null,
    priceText: "加密 300 / 開源 600",
    unit: "",
    badge: "",
    images: ["assets/img/dc/fivem-jobmap-1.jpg"],
    features: ["定位上班玩家座標", "需要新增職位座標可以新增"],
    details: [],
    notes: [],
  },
  {
    id: "fivem-custom",
    name: "代寫插件",
    category: "fivem",
    tagline: "需要寫插件的話，開工單詢問。",
    price: null,
    unit: "",
    badge: "",
    images: [],
    features: [],
    details: ["如果需要寫插件，請開工單作詢問。"],
    notes: [],
  },

  /* ------------------------------------------------------------ 免費區 */
  {
    id: "free-core-install",
    name: "警察模組及核心插件代裝",
    category: "free",
    tagline: "LSPDFR、Script Hook V、RageNativeUI 等核心，免費幫你裝。",
    price: 0,
    unit: "",
    badge: "免費",
    images: [],
    features: ["LSPD First Response", "Script Hook V", "RageNativeUI", "HeapAdjuster", "Packfile Limit Adjuster", "gameconfig（300 cars）"],
    details: ["若不了解如何安裝，歡迎開啟服務單，我們提供免費代裝警察模組及核心插件服務。目前版本 3889。"],
    notes: [],
  },
  {
    id: "free-helmet",
    name: "安全帽不脫落插件",
    category: "free",
    tagline: "戴著安全帽或帽子都不會自動脫掉。",
    price: 0,
    unit: "",
    badge: "免費",
    images: ["assets/img/dc/free-helmet-1.jpg", "assets/img/dc/free-helmet-2.jpg"],
    features: ["需要從 RAGEPluginHook 啟動此插件"],
    details: ["到 Discord「免費釋出插件🆓」頻道下載。"],
    notes: [],
  },
  {
    id: "free-taiwan-mdt",
    name: "台灣化車用電腦",
    category: "free",
    tagline: "Callout Interface 的警用電腦面板與台灣車牌面板台灣化。",
    price: 0,
    unit: "",
    badge: "免費",
    images: [],
    features: ["台灣化 Callout Interface 警用電腦面板", "台灣車牌面板", "安裝教學已包含在檔案內"],
    details: ["發佈在 LCPDFR.com，Discord「免費釋出插件🆓」頻道有連結。原模組為 Callout Interface。"],
    notes: [],
  },
];

/* 價目表（照 Discord「價目表」海報） */
const PRICE_LIST = [
  { item: "警察模組及核心插件代裝", price: 0,  unit: "" },
  { item: "插件代裝",               price: 10, unit: "個" },
  { item: "車輛代裝",               price: 10, unit: "輛" },
  { item: "服飾代裝",               price: 10, unit: "件" },
  { item: "武器代裝",               price: 15, unit: "把" },
  { item: "警笛包代裝",             price: 20, unit: "包" },
  { item: "警笛更改",               price: 50, unit: "個" },
  { item: "塗裝更改",               price: 50, unit: "張" },
  { item: "車輛修復",               price: 10, unit: "個" },
  { item: "崩潰修復",               price: 30, unit: "個" },
];

/* 常見問題 */
const FAQ = [
  { q: "怎麼買？", a: "到 Discord 的「🛎️服務單🛎️」頻道按「點我開啟服務單」，客服會在單裡處理。先付款後交貨，目前只接受轉帳。" },
  { q: "完全不會裝可以嗎？", a: "可以。警察模組跟核心插件免費代裝，其他商品代裝費用看價目表。" },
  { q: "警車可以換分局、車號嗎？", a: "可以，車牌、縣市、分局編號都免費自訂。" },
  { q: "中文翻譯要先準備什麼？", a: "要先自己下載原插件（LSPDFR、Stop The Ped 等），我們賣的是翻譯檔，不是原插件。" },
  { q: "FiveM 插件可以退款嗎？", a: "已交付、架構不符、與其他插件衝突、不會安裝、功能不符合需求，都不退款。購買前請先確認伺服器架構。" },
];
